// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bamptcmcktncnkkffgoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhbXB0Y21ja3RuY25ra2ZmZ29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTI4MDIsImV4cCI6MjA3MDc2ODgwMn0.-M_WQNleSkHDN5SCcsjgr0jILEtpYr_s2mymFVGXWr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});